import pyvips

from app.config import settings
from app.services.renditions import RENDITION_SPECS

# Allow-list of accepted input formats, checked via magic bytes before pyvips
# ever touches the buffer. Deliberately excludes SVG: Dockerfile.api compiles
# libvips with librsvg support, so without this check any attacker-supplied
# SVG markup would be rasterized (a classic XXE/entity-expansion/SSRF vector),
# as would TIFF/HEIF/PDF and anything else libvips happens to load.
_SIGNATURES: dict[str, tuple[bytes, ...]] = {
    "png": (b"\x89PNG\r\n\x1a\n",),
    "jpeg": (b"\xff\xd8\xff",),
    "gif": (b"GIF87a", b"GIF89a"),
}


class ImageValidationError(Exception):
    """Any client-input image problem: unsupported format, oversized
    dimensions, or a corrupt/truncated file pyvips can't decode."""


def sniff_format(data: bytes) -> str | None:
    for fmt, signatures in _SIGNATURES.items():
        if any(data.startswith(sig) for sig in signatures):
            return fmt
    if len(data) >= 12 and data[0:4] == b"RIFF" and data[8:12] == b"WEBP":
        return "webp"
    if len(data) >= 12 and data[4:8] == b"ftyp":
        major_brand = data[8:12]
        if major_brand in {b"heic", b"heix", b"hevc", b"hevx", b"mif1", b"msf1"}:
            return "heic"
        # AVIF was previously entirely unrecognized here (even though
        # file_validation.py's _is_avif already accepts it for the generic
        # /upload/file route) -- a legitimate AVIF upload to /upload/image,
        # a QR logo, or a poster-generation frame was rejected as
        # "unsupported format" for no reason other than this list never
        # having been extended to it.
        if major_brand in {b"avif", b"avis"}:
            return "avif"
    return None


def validate_and_strip_image(
    file_data: bytes, optimization: str = "balanced", *, generate_renditions: bool = False
) -> tuple[bytes, str, int, int, dict[str, bytes]]:
    """Load image using pyvips, strip metadata (EXIF), generate materialized
    thumbnail rendition if requested, and return the optimized bytes along with
    detected format, dimensions, and renditions buffers.

    `generate_renditions=False` skips rendition generation (returning an empty
    dict in its place) when the caller does not request a thumbnail.
    """
    if sniff_format(file_data) is None:
        raise ImageValidationError("Unsupported or unrecognized image format")

    try:
        image = pyvips.Image.new_from_buffer(file_data, "")
    except pyvips.Error as exc:
        raise ImageValidationError(f"Could not decode image: {exc}") from exc

    width = image.width
    height = image.height
    # libvips is demand-driven: new_from_buffer reads dimensions from the
    # header without materializing pixel data, so this check runs *before*
    # the expensive full-resolution decode that write_to_buffer triggers --
    # exactly where a decompression-bomb guard needs to sit.
    if width * height > settings.MAX_IMAGE_PIXELS:
        raise ImageValidationError(
            f"Image dimensions {width}x{height} exceed the {settings.MAX_IMAGE_PIXELS}-pixel limit"
        )

    # Materialize registered renditions when requested and in 'materialize' mode.
    # In 'on_demand' mode, renditions are skipped here and generated by imgproxy
    # on the fly at request time.
    # crop=CENTRE fill-crops to an exact box (for square thumbnail).
    # crop=NONE fits to width preserving aspect ratio, only encoding widths <= source width.
    # Each rendition uses its own (lower) `effort` -- see RenditionSpec's
    # docstring on that field for why this must not be the main encode's 6.
    renditions: dict[str, bytes] = {}
    if generate_renditions and settings.IMAGE_RENDITION_MODE == "materialize":
        for spec in RENDITION_SPECS.values():
            if spec.crop:
                rend_image = image.thumbnail_image(
                    spec.width, height=spec.height, crop=pyvips.Interesting.CENTRE
                )
            else:
                # Fit-to-width aspect preserving; only encode widths <= source width
                if width < spec.width:
                    continue
                rend_image = image.thumbnail_image(
                    spec.width,
                    height=10_000_000,
                    size=pyvips.Size.DOWN,
                    crop=pyvips.Interesting.NONE,
                )
            renditions[spec.name] = rend_image.write_to_buffer(
                f".{spec.format}",
                Q=spec.quality,
                strip=True,
                effort=spec.effort,
                smart_subsample=True,
            )

    # Determine quality, max dimension, and encode effort based on
    # optimization profile. Only "quality" pays libwebp's effort=6 (its
    # slowest, most exhaustive compression search) -- "size" and "balanced"
    # (the default, and what the vast majority of uploads use) get effort=4,
    # the same trade made for materialized renditions above: a little file
    # size for a large, synchronous-request-latency win. A caller that
    # explicitly asked for "quality" is opting into the slower encode; one
    # that didn't shouldn't pay for it by default.
    if optimization == "size":
        q_value = 65
        max_dim = 1280
        effort = 4
    elif optimization == "quality":
        q_value = 95
        max_dim = 3840
        effort = 6
    else:  # "balanced"
        q_value = 85
        max_dim = 1920
        effort = 4

    if width > max_dim or height > max_dim:
        scale = min(max_dim / width, max_dim / height)
        image = image.resize(scale)
        width = image.width
        height = image.height

    # Write to optimized webp format. strip=True removes ALL metadata
    # (EXIF/GPS, ICC profile, XMP) on output in a single call.
    # smart_subsample=True improves color sharpness for high contrast edges.
    optimized_buffer = image.write_to_buffer(
        ".webp", Q=q_value, strip=True, effort=effort, smart_subsample=True
    )
    return optimized_buffer, "image/webp", width, height, renditions
