version: '3.3'

services:
  api:
    image: gujadoesdocker/filemanager-fastapi
    build:
      context: ./api
      args:
      - INSTALL_FFMPEG=${INSTALL_FFMPEG}
    volumes:
    - './api/app:/app'
    command: /start.sh
    ports:
      - 9000:9000
    expose:
      - 9000

### Certbot #########################################
  certbot:
    image: phusion/baseimage:bionic-1.0.0
    build:
      context: ./certbot
    volumes:
      - ./data/certbot/certs/:/var/certs
      - ./certbot/letsencrypt/:/var/www/letsencrypt
    environment:
      - CN=${DOMAINS}
      - EMAIL=${SSL_DOMAIN_OWNER}

  ### NGINX Server #########################################
  nginx:
    image: nginx:alpine
    build:
      context: ./nginx
      args:
        - PYTHON_UPSTREAM_CONTAINER=${NGINX_PYTHON_UPSTREAM_CONTAINER}
        - PYTHON_UPSTREAM_PORT=${NGINX_PYTHON_UPSTREAM_PORT}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ./data/certbot/certs/:/var/certs
      - ./certbot/letsencrypt/:/var/www/letsencrypt
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - api