version: '3.3'

services:
  api:
    image: 127.0.0.1:5000/filemenager-fastapi
    build:
       context: ./api
       args:
        - INSTALL_FFMPEG=${INSTALL_FFMPEG}
    volumes:
    - './api/app:/app'
    command: /start-reload.sh
    ports:
      - 80:80
    expose:
      - 80