[tool.poetry]
name = "filemanager-fastapi"
version = "0.0.1"
description = "Fastapi with file management"
authors = ["JEX <guja1995@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.70.1"
uvicorn = ["0.12.0,<0.16.0"]
python-multipart = ["0.0.5,<0.0.6"]
gunicorn = "^20.1.0"
python-dotenv = "^0.19.2"
apache-libcloud = "^3.4.1"
Pillow-SIMD = "^8.4.0"
aiofiles = "^0.5.0"
cryptography = "^36.0.1"
ffmpeg-python = "^0.2.0"
qrcode = "^7.3.1"
python-magic = "^0.4.24"
pyjson5 = "^1.6.0"


[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
pytest = ["6.2.4,<7.0.0"]
pytest-asyncio = "^0.16.0"
httpx = ["0.14.0,<0.19.0"]

[build-system]
requires = ["poetry>=1.1.12"]
build-backend = "poetry.masonry.api"
